site_name: Bristol SU Portal
site_url: https://bristol-su.github.io/portal
repo_url: https://github.com/bristol-su/portal
edit_uri: edit/develop/docs/docs/
nav:
  - Introduction: index.md
  - Build an Activity:
    - New Activity: 'build/activity.md'
    - Adding Modules: 'build/module.md'
    - Logic Groups: 'build/logic.md'
    - Actions: 'build/actions.md'
  - Using the activities:
    - As a student: 'using/student.md'
    - As an admin: 'using/admin.md'
  - Modules:
    - File Upload: 'modules/file-upload.md'
    - Assign Roles: 'modules/assign-roles.md'
    - Data Entry: 'modules/data-entry.md'
    - Static Page: 'modules/static-page.md'
    - Typeform: 'modules/typeform.md'
theme:
  name: material
  features:
    - search.suggest
    - search.share
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      separator: "_"
  - attr_list
  - md_in_html
plugins:
  - search
  - git-authors
  - git-revision-date
extra:
  analytics:
    provider: google
    property: G-QYQYW0FYNM
