name: Deploy the portal
on:
  push:
    branches:
      - release/staging
jobs:
  vapor:
    name: Deploy to the staging site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
      - name: Create .npmrc
        uses: 'finnp/create-file-action@master'
        env:
          FILE_NAME: ".npmrc"
          FILE_DATA: "//npm.pkg.github.com/:_authToken=${{ github.token }}\n@bristol-su:registry=https://npm.pkg.github.com"
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
      - name: Deploy Environment
        run: vapor deploy staging
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
